# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
# board: [ "nice_nano_v2" ]
# shield: [ "corne_left", "corne_right" ]
# include:
#   - board: bdn9_rev2
#   - board: nice_nano_v2
#     shield: reviung41
#
---
include:
  - board: nrfmicro_13
    shield: [jorne_left, jorne_right]
    name: ["Jorne Blues", "Jorne Brass"]
    flags: ["screen"]
  - board: nrfmicro_13_52833
    shield: [jorne_left, jorne_right]
    name: ["Sporne"]
    flags: ["screen", "mem_constraint"]
  - board: nrfmicro_13_52833
    shield: [tbk_mini_left, tbk_mini_right]
    flags: ["studio"]
  - board: nrfmicro_13_52833
    shield: [jorne_left, jorne_right]
    name: ["RT-22"]
  - board: nrfmicro_13_52833
    shield: radpad
  - board: [jorian840_left, jorian840_right]
    name: ["Jorian840 Omron", "Jorian840 Cobalt", "wEnki44"]
    flags: ["studio"]
  - board: [skean_left, skean_right]
    name:
      [
        "Skean T1",
        "Skean Alps",
        "Skean DG",
        "Skean MA",
        "Skean i-Rocks",
        "Skean SKCC",
      ]
    flags: ["studio"]
  - board: [skean_left, skean_right]
    name: ["Skean Zilent"]
    debounce: 10
    flags: ["studio"]
  - board: [dao_left, dao_right]
  - board: [corneish_zen_v1_left, corneish_zen_v1_right]
    name: ["Zen gChoc"]
    flags: ["studio"]
  - board: [corneish_zen_v2_left, corneish_zen_v2_right]
    name: ["Zen Sunset"]
    flags: ["studio"]
  - board: seeeduino_xiao_ble
    shield: [ergonaut_one_left, ergonaut_one_right]
    flags: ["studio"]
  - board: [ilich_left, ilich_right]
    name:
      [
        "Il'ich T1",
        "Il'ich Alps",
        "Il'ich DG",
        "Il'ich MA",
        "Il'ich i-Rocks",
        "Il'ich SKCC",
      ]
    flags: ["studio"]
  - board: [ilich_left, ilich_right]
    name: ["Il'ich Zilent"]
    debounce: 10
    flags: ["studio"]
